-- TITLES
CREATE TABLE TITLES (title_id VARCHAR(10) NOT NULL PRIMARY KEY,
					 title VARCHAR(30) NOT NULL);

SELECT * FROM TITLES;

-- EMPLOYEES
CREATE TABLE EMPLOYEES (emp_no INT NOT NULL PRIMARY KEY,
					   emp_title_id VARCHAR(10) NOT NULL, 
					   FOREIGN KEY (emp_title_id) REFERENCES TITLES(title_id),
					   birth_date VARCHAR(20) NOT NULL,
					   first_name VARCHAR(30) NOT NULL,
					   last_name VARCHAR(30) NOT NULL,
					   sex VARCHAR(1) NOT NULL,
					   hire_date DATE NOT NULL);
					   
SELECT * FROM EMPLOYEES;

-- DEPARTMENTS 
CREATE TABLE DEPARTMENTS (dept_no VARCHAR(10) NOT NULL PRIMARY KEY,
						 dept_name VARCHAR(40) NOT NULL);
						 
SELECT * FROM DEPARTMENTS;

-- DEPT MANAGER
CREATE TABLE DEPT_MANAGER (dept_no VARCHAR(10) NOT NULL,
					  FOREIGN KEY (dept_no) REFERENCES DEPARTMENTS(dept_no),
					  emp_no INT NOT NULL, 
					  FOREIGN KEY (emp_no) REFERENCES EMPLOYEES(emp_no));

SELECT * FROM DEPT_MANAGER;

-- DEPT EMPLOYEES
CREATE TABLE DEPT_EMP (emp_no INT NOT NULL, 
					   dept_no VARCHAR(10) NOT NULL, 
					   PRIMARY KEY (emp_no, dept_no),
					  FOREIGN KEY (emp_no) REFERENCES EMPLOYEES(emp_no),
					  FOREIGN KEY (dept_no) REFERENCES DEPARTMENTS(dept_no));

SELECT * FROM DEPT_EMP;

-- SALARIES
CREATE TABLE SALARIES (emp_no INT NOT NULL,
					  FOREIGN KEY (emp_no) REFERENCES EMPLOYEES(emp_no),
					  salary INT NOT NULL);

SELECT * FROM SALARIES;

-- RESET AS NEEDED
-- DROP TABLE IF EXISTS SALARIES;
-- DROP TABLE IF EXISTS DEPT_EMP;
-- DROP TABLE IF EXISTS DEPT_MANAGER;
-- DROP TABLE IF EXISTS DEPARTMENTS;
-- DROP TABLE IF EXISTS EMPLOYEES;
-- DROP TABLE IF EXISTS TITLES;